CREATE TABLE visitors (
  id SERIAL PRIMARY KEY,
  ip INET NOT NULL,
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100),
  country_code CHAR(2),
  continent VARCHAR(50),
  zip VARCHAR(20),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  timezone VARCHAR(100),
  local_time TIMESTAMPTZ,
  is_eu_member BOOLEAN,
  is_dst BOOLEAN,
  org VARCHAR(255),
  asn INTEGER,
  asn_descr VARCHAR(255),
  asn_domain VARCHAR(255),
  asn_abuse_email VARCHAR(255),
  asn_type VARCHAR(50),
  company_name VARCHAR(255),
  company_type VARCHAR(50),
  company_domain VARCHAR(255),
  company_abuser_score VARCHAR(50),
  datacenter_name VARCHAR(255),
  datacenter_domain VARCHAR(255),
  datacenter_network VARCHAR(255),
  is_datacenter BOOLEAN,
  is_mobile BOOLEAN,
  is_satellite BOOLEAN,
  is_crawler BOOLEAN,
  is_tor BOOLEAN,
  is_proxy BOOLEAN,
  is_vpn BOOLEAN,
  is_abuser BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT now()
);